name: Deploy Lambda

on:
  push:
    branches:
      - main  # Trigger deployment only for pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: List contents to verify paths
    - name: List files in the directory
      run: ls -R

    # Step 4: Zip the 'task_created' Lambda function handler.py
    - name: Zip Task Created Lambda
      run: |
        cd listeners/task_created
        ls # List contents in the task_created folder to verify presence of handler.py
        zip ../../task_created_function.zip handler.py

    # Step 5: Deploy to Task Created Lambda
    - name: Deploy to Task Created Lambda
      run: |
        aws lambda update-function-code \
          --function-name CdkProjectStack-UserCreatedListener1045019B-BIW3g59OOHa5 \
          --zip-file fileb://task_created_function.zip

    # Step 6: Zip the 'task_updated' Lambda function handler.py
    - name: Zip Task Updated Lambda
      run: |
        cd listeners/task_updated
        ls # List contents in the task_updated folder to verify presence of handler.py
        zip ../../task_updated_function.zip handler.py

    # Step 7: Deploy to Task Updated Lambda
    - name: Deploy to Task Updated Lambda
      run: |
        aws lambda update-function-code \
          --function-name CdkProjectStack-TaskUpdatedListener15AE0FCC-mSbZnpQBroMd \
          --zip-file fileb://task_updated_function.zip

    # Step 8: Zip the 'user_created' Lambda function handler.py
    - name: Zip User Created Lambda
      run: |
        cd listeners/user_created
        ls # List contents in the user_created folder to verify presence of handler.py
        zip ../../user_created_function.zip handler.py

    # # Step 9: Deploy to User Created Lambda
    # - name: Deploy to User Created Lambda
    #   run: |
    #     aws lambda update-function-code \
    #       --function-name CdkProjectStack-UserCreatedListener1045019B-BIW3g59OOHa5 \
    #       --zip-file fileb://user_created_function.zip

    # exeption for step 9 
    # An error occurred (ResourceConflictException) when calling the UpdateFunctionCode operation: 
      # The operation cannot be performed at this time. An update is in progress for resource: 
      # arn:aws:lambda:***:774305574116:function:CdkProjectStack-UserCreatedListener1045019B-BIW3g59OOHa5

    # Step 10: Zip the Lambda function code, including the 'app' folder
    - name: Zip Lambda function
      run: zip -r function.zip app

    # Step 11: Deploy to AWS Lambda.
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name CdkProjectStack-FastAPILambdaFunctionC1ADADAF-A35BYbPR2gCp \
          --zip-file fileb://function.zip